### ISSUE TITLE
Hw5

### ISSUE THREAD

**Issue by rahlk** [juhidesai/x9115baymax#2]
Hey guys, your best energy is greater than 1. It should ideally lie between 0 and 1.

**Comment by RonakNisher** [comment]
Hey @rahlk , we normalized the scores (Updated screen prints in README too). The final energy is a little over 1 because the optimal energy we are getting is slightly higher than the max we get for that particular run.(We recalculate max and min in each run of the program) . Will this do or should I put in a higher known max value from previous runs ?

**Comment by rahlk** [comment]
Pardon me for the late response. You'll need to keep track of the max and min energies across all programs. It's still too large.
![image](https://cloud.githubusercontent.com/assets/1433964/10866225/2843cb2e-7ffc-11e5-97a9-d7f4e95555b5.png)

**Comment by RonakNisher** [comment]
Hey @rahlk , The above one is the old screen print. The readme has both the new as well as the old ones. Here is the updated one that we wanted to highlight. https://github.com/juhidesai/x9115baymax/blob/master/hw/code/5/mws_updated2.PNG
